require File.dirname(__FILE__) + '/../test_helper'

# LoginController was generated by the shopify_app plugin
# No real interest in writing tests for that stuff (unless something is going wrong)
#
# However, we added logic to the finalize action so we will test that action here.
class LoginControllerTest < ActionController::TestCase
  
  test "finalize success" do
    api_shop = ShopifyAPI::Shop.new
    api_shop.stubs(:name).returns('Foobar Shop')
    api_shop.stubs(:timezone).returns('(GMT-05:00) Eastern Time (US & Canada)')
    ShopifyAPI::Shop.stubs(:current).returns(api_shop)
    assert_difference 'Shop.count' do
      post 'finalize', :shop => 'foobar.myshopify.com', :t => 'token value'
    end
  end
end